### ISSUE TITLE
Problem with makeACDC and memory option

### ISSUE THREAD

**Issue by prozober** [CMSCompOps/WmAgentScripts#191]
We have this Montecarlo request https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=HIG-RunIISummer15wmLHEGS-00710, it had some 50660 exit codes, we need to increase memory to 10G.
When I run this:
`python makeACDC.py --all -m 10000 -w pdmvserv_HIG-RunIISummer15wmLHEGS-00710_00202_v0__161027_121520_2635`
I get:
```
Traceback (most recent call last):
  File "makeACDC.py", line 97, in <module>
    main()
  File "makeACDC.py", line 84, in main
    r = makeACDC(url, wfi, task, options.memory) 
  File "makeACDC.py", line 28, in makeACDC
    acdc = singleRecovery(url, task, initial.request, actions, do=True)
  File "/afs/cern.ch/user/p/prozober/scripts/testing/WmAgentScripts/Unified/recoveror.py", line 39, in singleRecovery
    if action.startswith('mem'):
AttributeError: 'list' object has no attribute 'startswith'
```

**Comment by vlimant** [comment]
please try the branch. we should merge it soon.
