### ISSUE TITLE
Problem with assign.py on third ACDC round

### ISSUE THREAD

**Issue by prozober** [CMSCompOps/WmAgentScripts#192]
For the third ACDC round of this Rereco I ran:
`python assign.py -s acdc -w prozober_ACDC2_Run2016B-v2-DisplacedJet-23Sep2016_8020_161031_205552_6055` 

The script stays quiet, no output, no exceptions. When I stop the process (Ctrl+C),  I get:

```
Traceback (most recent call last):
  File "assign.py", line 374, in <module>
    main()
  File "assign.py", line 205, in main
    ancestor_wf = workflowInfo(url, original_wf.request['OriginalRequestName'])
  File "/afs/cern.ch/user/p/prozober/scripts/testing/WmAgentScripts/utils.py", line 3164, in __init__
    raise Exception("Failed to get workload cache for %s"%workflow)
Exception: Failed to get workload cache for prozober_ACDC_Run2016B-v2-DisplacedJet-23Sep2016_8020_161028_101541_1091
```

**Comment by prozober** [comment]
I did some tests, they were successful.
