### ISSUE TITLE
KeyError: 'action' in assign.py

### ISSUE THREAD

**Issue by prozober** [CMSCompOps/WmAgentScripts#213]
I am trying to assign this ACDC https://cmsweb.cern.ch/reqmgr2/fetch?rid=prozober_ACDC0_task_EXO-PhaseIIFall16GS82-00043__v1_T_170308_143423_2512

`python assign.py -s acdc -w prozober_ACDC0_task_EXO-PhaseIIFall16GS82-00043__v1_T_170308_143423_2512`

Then this error appears
```
Traceback (most recent call last):
  File "assign.py", line 385, in <module>
    main()
  File "assign.py", line 379, in main
    multicore=multicore
  File "assign.py", line 81, in assignRequest
    res = reqMgr.assignWorkflow(url, workflow, team, params)
  File "/afs/cern.ch/user/p/prozober/scripts/latest/WmAgentScripts/reqMgrClient.py", line 921, in assignWorkflow
    res = setWorkflowAssignment(url, workflowname, defaults)
  File "/afs/cern.ch/user/p/prozober/scripts/latest/WmAgentScripts/reqMgrClient.py", line 1251, in setWorkflowAssignment
    schema = reqmgr1_to_2_Assignment(schema)
  File "/afs/cern.ch/user/p/prozober/scripts/latest/WmAgentScripts/reqMgrClient.py", line 1219, in reqmgr1_to_2_Assignment
    if params['action'] == 'Assign':
KeyError: 'action'
```

Could you please take a look?

**Comment by vlimant** [comment]
I indeed moved unified to assign using directly reqmgr2 schema, I tried to do it carefully and not impact assign.py but it seems that I failed ... 
https://github.com/CMSCompOps/WmAgentScripts/commit/a8f06fcf5d8fb43aee8fabee27768c815b3d0732 should fix it

**Comment by prozober** [comment]
it worked! thank you.
