### ISSUE TITLE
HTTP Proxy error for checkor and recovery script

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#395]
We are having dbs accessing issues for checkor and getDatasetPresence. Also, while running the recovery.py script, I am getting the same issues.

```
failed on pdmvserv_task_BPH-RunIIFall17GS-00088__v1_T_181020_191004_7538 due to HTTP Error 502: Proxy Error and Traceback (most recent call last):
File "Unified/checkor.py", line 345, in run
self.check()
File "Unified/checkor.py", line 774, in check
parentage[out] = findParent( out )
File "/data/unified/WmAgentScripts/Unified/utils.py", line 4937, in findParent
ret = dbsapi.listDatasetParents( dataset= dataset)
File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/dbs3-client/3.5.1/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 800, in listDatasetParents
return self.__callServer("datasetparents", params=kwargs)
File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/dbs3-client/3.5.1/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 194, in __callServer
self.__parseForException(http_error)
File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/dbs3-client/3.5.1/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 218, in __parseForException
raise http_error
HTTPError: HTTP Error 502: Proxy Error
```
recovery.py error
```
Starting recovery procedure for prebello_Run2018D-v1-SingleMuon-28Feb2019_1040p1_190228_025815_4422
python recoverMissingLumis.py -q sagarwal -g DATAOPS -f -r prebello_Run2018D-v1-SingleMuon-28Feb2019_1040p1_190228_025815_4422
Exception in thread Thread-131:
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.12.patch4/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "recoverMissingLumis.py", line 291, in run
    dbsReader = DBSReader(endpoint=self.dbs)
  File "/data/srv/wmagent/v1.1.12.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.12.patch4/lib/python2.7/site-packages/WMCore/Services/DBS/DBSReader.py", line 23, in DBSReader
    raise DBSReaderError("Can't contact DBS at %s, got errors %s" % (endpoint, msg))
DBSReaderError: DBSReaderError
Message: Can't contact DBS at https://cmsweb.cern.ch/dbs/prod/global/DBSReader, got errors Instantiating DBS3Reader failed with HTTP Error 502: Proxy Error

	ModuleName : WMCore.Services.DBS.DBSErrors
	MethodName : __init__
	ClassInstance : None
	FileName : /data/srv/wmagent/v1.1.12.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.12.patch4/lib/python2.7/site-packages/WMCore/Services/DBS/DBSErrors.py
	ClassName : None
	LineNumber : 38
	ErrorNr : 1002
```

fatal exception in getDatasetPresence for /ADDGravToGG_NegInt-0_LambdaT-5000_M-500To1000_TuneCP2_13TeV-pythia8/RunIIFall17GS-93X_mc2017_realistic_v3-v1/GEN-SIM
HTTP Error 502: Proxy Error

@vlimant @thongonary Can you please have a look?

**Comment by sharad1126** [comment]
fatal exception in getDatasetPresence for /SUSYGluGluToBBHToTauTau_M-600_TuneCP5_13TeV-amcatnlo-pythia8/RunIIFall17NanoAOD-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/NANOAODSIM
(58, 'unable to use client certificate (no key found or wrong pass phrase?)')

@thongonary FYI

**Comment by thongonary** [comment]
@drkovalskyi I think this is another reason for a public account with common certificate.

**Comment by vlimant** [comment]
fact checking 2 cents : service proxy or user proxy is the same for any service.
that error does not look related to the user certificate being used, but the "client certificate", either the host, or something on cmsweb end.
if it's the proxy (which it is not) everything would fail (which does not)

**Comment by sharad1126** [comment]
I just made a recovery with the script(recovery.py) for another request and that worked perfectly.

```
[sagarwal@vocms0275 WmAgentScripts]$ python recovery.py --assign "--site T2_IN_TIFR --xrootd --lumisperjob 1" --w prebello_Run2018C-v1-DoubleMuonLowPU-28Feb2019_1040p1_190228_024742_2121 --go
Starting recovery procedure for prebello_Run2018C-v1-DoubleMuonLowPU-28Feb2019_1040p1_190228_024742_2121
python recoverMissingLumis.py -q sagarwal -g DATAOPS -f -r prebello_Run2018C-v1-DoubleMuonLowPU-28Feb2019_1040p1_190228_024742_2121
Created JSON r-0-Run2018C-v1-DoubleMuonLowPU-28Feb2019_1040p1.json for recovery of ['/DoubleMuonLowPU/Run2018C-28Feb2019-v1/RECO']
This will recover 9 lumis in 9 files
python reqMgrClient.py -j r-0-Run2018C-v1-DoubleMuonLowPU-28Feb2019_1040p1.json
1 that can be submitted
./assign.py --site T2_IN_TIFR --xrootd --lumisperjob 1 --w sagarwal_r-0-Run2018C-v1-DoubleMuonLowPU-28Feb2019_1040p1_190320_161026_5258
Assigned workflow: sagarwal_r-0-Run2018C-v1-DoubleMuonLowPU-28Feb2019_1040p1_190320_161026_5258 to site: ['T2_IN_TIFR'] and team production
Assigned workflow: sagarwal_r-0-Run2018C-v1-DoubleMuonLowPU-28Feb2019_1040p1_190320_161026_5258 to site: ['T2_IN_TIFR'] with processing version 1
```

**Comment by sharad1126** [comment]
It finally worked. Guess it was some DBS issue from cmsweb end
