### ISSUE TITLE
json valuerror not easy to understand

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#412]
should we change json.load to simplejson.load for assignor.py to understand where it fails @vlimant @thongonary ?.

This is log from today morning when the module failed(2019-04-29_08:25:17.log). 
```
dynamo lock acquired True
Option Early is on
getting wf in considered
0
getting wf in staging
27
getting wf in staged
30
Traceback (most recent call last):
  File "Unified/assignor.py", line 690, in <module>
    assignor(url,spec, options=options)
  File "Unified/assignor.py", line 67, in assignor
    all_stuck.update( json.loads( open('%s/stuck_transfers.json'%monitor_pub_dir).read() ))
  File "/data/srv/wmagent/v1.1.10.patch3/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/data/srv/wmagent/v1.1.10.patch3/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/srv/wmagent/v1.1.10.patch3/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Abnormal termination with exit code 0
Mon Apr 29 08:33:04 CEST 2019
```

**Comment by thongonary** [comment]
Usually it just means the json file is empty, likely due to EOS issue. Ideally there should be a protection to make it fail gracefully.

**Comment by sharad1126** [comment]
The same id happening for assignor again since noon today.

**Comment by sharad1126** [comment]
For assignor, what I can understand is, that we are getting this error while trying to find the aaa_mapping.
I print out once the json outputs and it fails after printing dataset_endpoints.
