### ISSUE TITLE
remaining_*_.html issues

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#442]
remainor module is not updating all the sites frequently. Also, while running it manually for single site, it gives an error:
```
T1_ES_PIC_Disk has 0 [TB] left out of 833
[Site Threads] Processing 1 threads with 5 max concurrent and timeout None [min]
checking on site T1_ES_PIC_Disk
[T1_ES_PIC_Disk Dataset Threads] Processing 7424 threads with 10 max concurrent and timeout None [min]
Traceback (most recent call last):
  File "Unified/remainor.py", line 276, in <module>
    parse( options )
  File "Unified/remainor.py", line 237, in parse
    run_threads.run()
  File "/data/unified/WmAgentScripts/Unified/utils.py", line 1691, in run
    self._run()
  File "/data/unified/WmAgentScripts/Unified/utils.py", line 1787, in _run
    get_eta()
  File "/data/unified/WmAgentScripts/Unified/utils.py", line 1727, in get_eta
    display_time(total_expected),
UnboundLocalError: local variable 'total_expected' referenced before assignment
```

the remaining html file updation could be due to gwmsmon* json files issues it is facing from time to time. @thongonary  FYI

**Comment by haozturk** [comment]
We do not run remainor anymore, so closing this issue.
