### ISSUE TITLE
rejector module gives error while using personal account 

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#499]
**Impact of the bug**
Doesn't informs McM about rejection. Not sure about the set_trouble status and dataset -k option. 

**Describe the bug**
```
[sagarwal@vocms0275 WmAgentScripts]$ python Unified/rejector.py --set_trouble -k pdmvserv_task_HIG-RunIIFall18wmLHEGS-02502__v1_T_200115_210357_8152
Using the rw account
checking on cmsr
1 to reject
invalidating the workflow by unified operator sagarwal
checking wf family: pdmvserv_task_HIG-RunIIFall18wmLHEGS-02502__v1_T_200115_210357_8152 running-closed [u'/VBFToHiggs0Mf05ph0ToZZTo4l_M125_GaSM_TuneCP5_13TeV_JHUGenV730_MCFM701_pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM', u'/VBFToHiggs0Mf05ph0ToZZTo4l_M125_GaSM_TuneCP5_13TeV_JHUGenV730_MCFM701_pythia8/RunIIAutumn18NanoAODv6-Nano25Oct2019_102X_upgrade2018_realistic_v20-v1/NANOAODSIM']
checking wf family: pdmvserv_task_HIG-RunIIFall18wmLHEGS-02502__v1_T_200115_210357_8152 aborted [u'/VBFToHiggs0Mf05ph0ToZZTo4l_M125_GaSM_TuneCP5_13TeV_JHUGenV730_MCFM701_pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM', u'/VBFToHiggs0Mf05ph0ToZZTo4l_M125_GaSM_TuneCP5_13TeV_JHUGenV730_MCFM701_pythia8/RunIIAutumn18NanoAODv6-Nano25Oct2019_102X_upgrade2018_realistic_v20-v1/NANOAODSIM']
pdmvserv_task_HIG-RunIIFall18wmLHEGS-02502__v1_T_200115_210357_8152 already aborted
pdmvserv_task_HIG-RunIIFall18wmLHEGS-02502__v1_T_200115_210357_8152 rejected
Using sso-cookie file /afs/cern.ch/user/s/sagarwal/private/prod-cookie.txt
ERROR
Traceback (most recent call last):
  File "/data/unified/WmAgentScripts/Unified/McMClient.py", line 77, in get
    d=json.loads(self.response())
  File "/data/srv/wmagent/v1.1.12.patch4/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/data/srv/wmagent/v1.1.12.patch4/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/srv/wmagent/v1.1.12.patch4/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://login.cern.ch/adfs/ls/?wa=wsignin1.0&amp;wreply=https%3A%2F%2Fcms-pdmv.cern.ch%2FShibboleth.sso%2FADFS&amp;wct=2020-03-08T13%3A12%3A47Z&amp;wtrealm=https%3A%2F%2Fcms-pdmv.cern.ch%2FShibboleth.sso%2FADFS&amp;wctx=cookie%3A1583673167_ad11">here</a>.</p>
</body></html>

could not notify back to requestor
'NoneType' object is not iterable
could not notify back to requestor
'NoneType' object is not iterable

```
**How to reproduce it**
use the rejector.py on a workflow.

**Expected behavior**
Shouldn't give the above JSON error, and cookie errors. 

**Additional context and error message**
Probably something @jenimal can start working on and will give you a hands on into unified code as well.

**Comment by vlimant** [comment]
your sso cookie is outdated

**Comment by sharad1126** [comment]
got it. Thanks.
