### ISSUE TITLE
rejector is not running from vocms0275 and vocms0277

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#525]
**Impact of the bug**
Running rejector script gives segmentation fault and so script doesn't returns what it is suppose to. 

**Describe the bug**
sqlalchemy is a dependency which is used from the wmagent inside the machines. vocms0275 and vocms0277 uses the latest wmagent version. This could be a reason for the issue. 

**How to reproduce it**
running rejector.py in any of the two machines. 

**Expected behavior**
scripts should run without this error

**Additional context and error message**
```
[sagarwal@vocms0275 WmAgentScripts]$ python Unified/rejector.py -c pdmvserv_task_HIN-HINPbPbAutumn18pLHE-00013__v1_T_200320_013001_540
Using the rw account
checking on cmsr
ORA-24550: signal received: [si_signo=11] [si_errno=0] [si_code=1] [si_int=511004996] [si_ptr=0x7f3d1e755144] [si_addr=0x2f8]
kpedbg_dmp_stack()+362<-kpeDbgCrash()+192<-kpeDbgSignalHandler()+119<-skgesig_sigactionHandler()+218<-__sighandler()<-nspsend()+945<-nsdofls()+549<-nsdoacts()+257<-nsdo()+3723<-nsbasic_sd()+44<-nssend()+85<-nioqsm()+447<-nioqrs()+465<-ttcdrv()+3612<-nioqwa()+61<-upirtrc()+1378<-upirtr()+161<-kpurcs()+34<-kpuoc_openCursor()+40<-kpuds_DescStmt()+423<-kpudrefc()+97<-kpugattr()+7077<-OCIAttrGet()+9<-Cursor_PerformDefine()+52
Segmentation fault (core dumped)
```

```
[sagarwal@vocms0277 WmAgentScripts]$ python Unified/rejector.py -c pdmvserv_task_HIN-HINPbPbAutumn18pLHE-00013__v1_T_200320_013001_540
Using the rw account
checking on cmsr
ORA-24550: signal received: [si_signo=11] [si_errno=0] [si_code=1] [si_int=0] [si_ptr=(nil)] [si_addr=0x4]
kpedbg_dmp_stack()+362<-kpeDbgCrash()+192<-kpeDbgSignalHandler()+119<-skgesig_sigactionHandler()+218<-__sighandler()<-nsbasic_brc()+395<-nsbrecv()+69<-nioqar()+281<-nioqrs()+533<-ttcdrv()+3612<-nioqwa()+61<-upirtrc()+1378<-kpurcsc()+98<-kpuexec()+10790<-OCIStmtExecute()+39<-Cursor_InternalExecute()+82
Segmentation fault (core dumped)
[sagarwal@vocms0277 WmAgentScripts]$ python Unified/rejector.py -c pdmvserv_task_HIN-HINPbPbAutumn18pLHE-00013__v1_T_200320_013001_540
Using the rw account
checking on cmsr
ORA-24550: signal received: [si_signo=11] [si_errno=0] [si_code=1] [si_int=0] [si_ptr=(nil)] [si_addr=0x55]
kpedbg_dmp_stack()+362<-kpeDbgCrash()+192Traceback (most recent call last):
  File "Unified/rejector.py", line 306, in <module>
    rejector(url, spec, options)
  File "Unified/rejector.py", line 33, in rejector
    wfs = session.query(Workflow).filter(Workflow.name.contains(specific)).all()
  File "/data/srv/wmagent/v1.3.0/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/1.3.3/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3161, in all
    return list(self)
  File "/data/srv/wmagent/v1.3.0/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/1.3.3/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "/data/srv/wmagent/v1.3.0/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/1.3.3/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/data/srv/wmagent/v1.3.0/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/1.3.3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/data/srv/wmagent/v1.3.0/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/1.3.3/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/data/srv/wmagent/v1.3.0/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/1.3.3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/data/srv/wmagent/v1.3.0/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/1.3.3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/data/srv/wmagent/v1.3.0/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/1.3.3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/data/srv/wmagent/v1.3.0/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/1.3.3/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/data/srv/wmagent/v1.3.0/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/1.3.3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/data/srv/wmagent/v1.3.0/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/1.3.3/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-03106: fatal two-task communication protocol error
[SQL: SELECT cms_unified_admin."WORKFLOW".id AS "cms_unified_admin_WORKFL_1", cms_unified_admin."WORKFLOW".name AS "cms_unified_admin_WORKFL_2", cms_unified_admin."WORKFLOW".status AS "cms_unified_admin_WORKFL_3", cms_unified_admin."WORKFLOW".wm_status AS "cms_unified_admin_WORKFL_4" 
FROM cms_unified_admin."WORKFLOW" 
WHERE (cms_unified_admin."WORKFLOW".name LIKE '%' || :name_1 || '%')]
[parameters: {u'name_1': 'pdmvserv_task_HIN-HINPbPbAutumn18pLHE-00013__v1_T_200320_013001_540'}]
(Background on this error at: http://sqlalche.me/e/4xp6)
<-kpeDbgSignalHandler()+119<-skgesig_sigactionHandler()+218<-__sighandler()<-ttcpip()+7319<-ttcdrv()+958<-nioqwa()+61<-upirtrc()+1378<-kpurcsc()+98<-kpuexec()+10790<-OCIStmtExecute()+39<-Cursor_InternalExecute()+82
Segmentation fault (core dumped)
[sagarwal@vocms0277 WmAgentScripts]$ 
```

@amaltaro @z4027163 @vlimant fyi

**Comment by sharad1126** [comment]
Made a ticket for the oracle db team too but looks like this is more of a client side issue. https://cern.service-now.com/service-portal/view-incident.do?n=INC2377824

Alan mentioned on slack:
```
actually, you only see wmcore in the traceback because Unified uses the sqlAlchemy python library, which is shipped with WMAgent
it’s an unmaintained dependency that Unified has, it should be done through pypi
```

**Comment by sharad1126** [comment]
Looks like when we comment out 
```
up = componentInfo(soft=['wtc','jira'])
```
the script runs without issues. this means the session for the component info is somewhat conflicting with the new session made by rejector.

**Comment by sharad1126** [comment]
@z4027163 did you try to figure this out what should we do here?
@vlimant any suggestions please?

**Comment by vlimant** [comment]
Interference of

```
vlimant@vocms0268.cern.ch >python
Python 2.7.13+ (default, Apr 19 2017, 13:15:19)
[GCC 6.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Could not open PYTHONSTARTUP
IOError: [Errno 2] No such file or directory: '/afs/cern.ch/user/v/vlimant/.pythonrc'
>>> import sqlalchemy
>>> sqlalchemy.__version__
'0.9.6'
>>> sqlalchemy.__path__
['/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy']
>>>
vlimant@vocms0268.cern.ch >logout
Connection to vocms0268 closed.
vlimant@vocms0275.cern.ch >python
Python 2.7.13+ (default, Dec 18 2018, 10:09:09)
[GCC 6.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Could not open PYTHONSTARTUP
IOError: [Errno 2] No such file or directory: '/afs/cern.ch/user/v/vlimant/.pythonrc'
>>> import sqlalchemy
>>> sqlalchemy.__version__
'1.3.3'
>>> sqlalchemy.__path__
['/data/srv/wmagent/v1.3.0.patch1/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/1.3.3/lib/python2.7/site-packages/sqlalchemy']
>>>
```

and 

f3856274001f3ea533ecbdbc1c8620a8827c334f

there's probably some deep python knowledge to be extracted from understanding exactly what is going on. No time for this
