### ISSUE TITLE
cachor is not able to find dbs from vocms0269

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#570]
**Impact of the bug**
cachor module is failing again and again due to dbs not being found. 

**Describe the bug**
all modules on vocms0269.cern.ch are running without issues and able to access the dbs component but cachor is saying x509 issues.

**How to reproduce it**
```
checking on dbs
The dbs component is unreachable from vocms0269.cern.ch
Traceback (most recent call last):
  File "/data/unified/WmAgentScripts/Unified/utils.py", line 1147, in check
    getattr(self,'check_%s'%component)()
  File "/data/unified/WmAgentScripts/Unified/utils.py", line 1096, in check_dbs
    dbsapi = DbsApi(url=dbs_url)
  File "/data/srv/wmagent/v1.1.10.patch3/sw/slc7_amd64_gcc630/cms/dbs3-client/3.5.1/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 163, in __init__
    self.rest_api = RestApi(auth=X509Auth(ssl_cert=cert, ssl_key=key, ssl_verifypeer=verifypeer, ca_info=ca_info),
  File "/data/srv/wmagent/v1.1.10.patch3/sw/slc7_amd64_gcc630/cms/dbs3-pycurl-client/3.5.1/lib/python2.7/site-packages/RestClient/AuthHandling/X509Auth.py", line 14, in __init__
    self.__search_cert_key()
  File "/data/srv/wmagent/v1.1.10.patch3/sw/slc7_amd64_gcc630/cms/dbs3-pycurl-client/3.5.1/lib/python2.7/site-packages/RestClient/AuthHandling/X509Auth.py", line 83, in __search_cert_key
    raise ClientAuthException("No valid X509 cert-key-pair found.")
ClientAuthException: 'No valid X509 cert-key-pair found.'

dbs is unreachable
'No valid X509 cert-key-pair found.'
componentCheck finished
componentInfo, going with
False
finished
Fri May 29 12:26:48 CEST 2020
```

**Expected behavior**
dbs component is working properly without issues for all other modules. shouldn't affect cachor as well. 

**Additional context and error message**
@z4027163 fyi @amaltaro  any suggestions what could be wrong here?

**Comment by amaltaro** [comment]
is it possible you did not have the X509_* environment variables when this module got started?
This is what the traceback suggests.

**Comment by sharad1126** [comment]
but we run credentials.sh and every other module running in the machine 0269 is able to get the x509 environment variable.

**Comment by sharad1126** [comment]
ok I manually ran it. should be ok now.

**Comment by sharad1126** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/b5e8f30f127dc89583e59f1dcb0b5133d88304dd was recently added to the `cachor` module

**Comment by sharad1126** [comment]
@vlimant is there a reason to check all components for `cachor`, it just uses phedex component!

**Comment by z4027163** [comment]
It seems the cachor uses the transferStatuses(), which relies only on mongoDB to get the phedexid.

**Comment by vlimant** [comment]
I'd add source $BASE_DIR/credentials.sh in https://github.com/CMSCompOps/WmAgentScripts/blob/master/set.sh
cachor is not run within a xyz.sh like some other modules.

BTW : cachor is related to transferor and stagor.

**Comment by sharad1126** [comment]
@amaltaro yeah I actually tried to run it manually and saw the same and was going to make a PR to remove this module as it checks the cached phedex transfer requests status which we don't need now.
