### ISSUE TITLE
mcm component is failing 

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#575]
**Impact of the bug**
McM component is failing from every machine. 

**Describe the bug**
The mcm component is unreachable from vocms0269.cern.ch

**How to reproduce it**
```
[cmsunified@vocms0275 WmAgentScripts]$ python
Python 2.7.13+ (default, Dec 18 2018, 10:09:09) 
[GCC 6.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from utils import componentCheck
>>> c = componentCheck()
>>> c.check_mcm()
Using sso-cookie file /tmp/cmsunified-vocms0275.cern.ch-vfsvdka573t
ERROR
Traceback (most recent call last):
  File "McMClient.py", line 77, in get
    d=json.loads(self.response())
  File "/data/srv/wmagent/v1.3.0.patch1/sw/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/data/srv/wmagent/v1.3.0.patch1/sw/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/srv/wmagent/v1.3.0.patch1/sw/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://login.cern.ch/adfs/ls/?wa=wsignin1.0&amp;wreply=https%3A%2F%2Fcms-pdmv.cern.ch%2FShibboleth.sso%2FADFS&amp;wct=2020-06-04T13%3A28%3A30Z&amp;wtrealm=https%3A%2F%2Fcms-pdmv.cern.ch%2FShibboleth.sso%2FADFS&amp;wctx=cookie%3A1591277310_479d">here</a>.</p>
</body></html>

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "utils.py", line 1093, in check_mcm
    raise Exception("mcm is corrupted")
Exception: mcm is corrupted
>>> 
```
**Expected behavior**
mcm client is not behaving as expected

**Additional context and error message**
@z4027163 @vlimant any idea why this started happening suddenly?

**Comment by sharad1126** [comment]
Justinas suggested 2-3 things but none of them work as well:
1. to add `self.curl.setopt(pycurl.FOLLOWLOCATION, 1)` in McM client py file. 
2. change `if not os.path.isfile(self.cookieFilename):` to `if True:`

but after doing both the changes, it still fails.

**Comment by sharad1126** [comment]
the browser verifies that `https://cms-pdmv.cern.ch/mcm/` is working though.

**Comment by sharad1126** [comment]
After discussing more, we figured out that it works without any env variables without any issues. so probably the componentCheck() which needs env variables messes up with the mcmclient from time to time. @z4027163 fyi
```
[sagarwal@vocms0275 WmAgentScripts]$ python
Python 2.7.5 (default, Apr  2 2020, 13:16:51) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from McMClient import McMClient
>>> mcmC = McMClient(dev=False)
Using sso-cookie file /afs/cern.ch/user/s/sagarwal/private/prod-cookie.txt
>>> test = mcmC.getA('requests',page=0)
>>> len(test)
20
```

**Comment by sharad1126** [comment]
copied as a back and removed the prod-cookies.txt file in ~/private and it looks like it worked without issues now.

**Comment by haozturk** [comment]
McM component is working fine now, so closing this issue.
