### ISSUE TITLE
cmsunified certificate expiration

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#757]
**Impact of the bug**
This is an already solved issue, I am creating it for the record. It affects all the unified modules

**Describe the bug**
When voms certificate of `cmsunified` account expires, all the unified modules fail. Here is an example error that we got during the incident:
```
Traceback (most recent call last):
  File "/data/unified/WmAgentScripts/Unified/utils.py", line 1155, in check
    getattr(self,'check_%s'%component)()
  File "/data/unified/WmAgentScripts/Unified/utils.py", line 1109, in check_dbs
    blocks = dbsapi.listBlockSummaries( dataset = '/TTJets_mtop1695_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM', detail=True)
  File "/data/srv/wmagent/v1.4.3.patch2/sw/slc7_amd64_gcc630/cms/dbs3-client/3.16.0/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 137, in wrapper
    return func(*args, **kwargs)
  File "/data/srv/wmagent/v1.4.3.patch2/sw/slc7_amd64_gcc630/cms/dbs3-client/3.16.0/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 695, in listBlockSummaries
    return self.__callServer('blocksummaries', params=kwargs)
  File "/data/srv/wmagent/v1.4.3.patch2/sw/slc7_amd64_gcc630/cms/dbs3-client/3.16.0/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 201, in __callServer
    self.http_response = method_func(self.url, method, params, data, request_headers)
  File "/data/srv/wmagent/v1.4.3.patch2/sw/slc7_amd64_gcc630/cms/dbs3-pycurl-client/3.16.0/lib/python2.7/site-packages/RestClient/RestApi.py", line 34, in get
    return http_request(self._curl)
  File "/data/srv/wmagent/v1.4.3.patch2/sw/slc7_amd64_gcc630/cms/dbs3-pycurl-client/3.16.0/lib/python2.7/site-packages/RestClient/RequestHandling/HTTPRequest.py", line 57, in __call__
    curl_object.perform()
error: (35, 'error:14094415:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate expired')
```

**How to reproduce it**
Check unified logs when the cert is expired

**Expected behavior**
Renew the cert before it expires and set the correct configurational fields in unified machines

**Additional context and error message**
None

**Comment by haozturk** [comment]
Solution: 
- Replace the content of the following files with the `.pem` files of the renewed certificate.
```
/afs/cern.ch/user/c/cmsunified/.globus/hostcert/servicekey-vocms0268.pem
/afs/cern.ch/user/c/cmsunified/.globus/hostcert/servicecert-vocms0268.pem
```
